# Site settings
title: My memopad
email: A252.512297210@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my memopad, which consists of things that I want to share with you.Cheers!
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
